# Generated by Django 4.2.13 on 2024-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("items_json", models.CharField(max_length=5000)),
                ("name", models.CharField(max_length=900)),
                ("Email", models.CharField(max_length=1111)),
                ("address", models.CharField(max_length=11111)),
                ("city", models.CharField(max_length=1111)),
                ("state", models.CharField(max_length=1111)),
                ("zip_code", models.CharField(max_length=1111)),
            ],
        ),
    ]
