# Generated by Django 4.2.13 on 2024-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="Email",),
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orders",
            name="email",
            field=models.CharField(default="", max_length=1111),
        ),
    ]
