# Generated by Django 4.2.13 on 2024-07-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_orders_email_orders_phone_orders_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
